---
title: "Appendix: Constructing Prior Distributions Conditional on Constraints"
author: "Jason Hilton, Erengul Dodd, Jonathan J. Forster, Peter W. F. Smith"
output:
  pdf_document:
    keep_tex: yes
    pandoc_args:
    - --filter
    - pandoc-fignos
    - --filter
    - pandoc-eqnos
    - --smart
---


*Supplemental Material to "Projecting UK Mortality using Bayesian Generalised Additive Models"*


## Period Parameters {-}

This section describes how prior distributions for the period constraints are constructed.
Some details are repeated from the body of the text for completeness.
Period innovations are normally distributed so that:

$$
\begin{aligned}
\kappa_t &= \kappa_{t-1} + \epsilon_t \\
\epsilon_t &\sim \text{Normal}(0, \sigma_{\epsilon}^{2}) \\
\end{aligned}
$$
Defining $T$ as the number of periods in the dataset, the $2$ by $T$ matrix $C$ describes the two constraints on the vector of $\pmb{\kappa}$ parameters, that they must sum to zero and show no linear growth. 
$$
C = \begin{bmatrix}
1 & 1 & 1 & 1 & \dots & 1 & 1 \\
0 & 1 & 2 & 3 & \dots & T-2 & T-1 \\
\end{bmatrix}
$$
When the constraints hold,
$$
\begin{aligned}
C\pmb{\kappa} &= \pmb{0} \\
CS\pmb{\epsilon} &= \pmb{0},
\end{aligned}
$$ where $S$ is the cumulative sum matrix. A distribution for period innovations conditional on the constraints is obtained by first transforming $\pmb{\epsilon}$ into a new set of parameters $\pmb{\eta}$, where the first two elements of $\pmb{\eta}$ are zero when the constraints hold, and the remaining elements are identical to the equivalents in $\pmb{\epsilon}$. The matrix $Z$ used for this transformation is a $T$ by $T$ identity matrix with the first two rows replaced by the matrix $CS$.

$$
\begin{aligned}
\pmb{\eta} &= \begin{bmatrix}
\pmb{\eta^{\dagger}} \\
\pmb{\eta^{*}}
\end{bmatrix} = Z\pmb{\epsilon} \\ 
\pmb{\eta} &\sim \text{MVN}(\pmb{0}, ZZ^{T}\sigma_{\kappa}).
\end{aligned}
$$
By conditioning on the first two values of $\pmb{\eta}$ (denoted $\pmb{\eta}^{\dagger}$) equalling zero, we can find the distribution of the last $t-2$ elements of $\pmb{\eta}$ using the standard conditional relationship for multivariate normal variables. Conditioning on these elements of $\pmb{\eta}$ being equal to zero is equivalent to conditioning on the constraints holding. We can therefore calculate the values of the first two values of $\pmb{\epsilon}$ by multiplying $\pmb{\eta}$ by the inverse of the $Z$ matrix.

$$
\begin{aligned}
\Sigma &= ZZ^T{}\sigma^{2}_{\epsilon} \\
\pmb{\eta{*}} | (\pmb{\eta{\dagger}} = \textbf{0}) &\sim \text{MVN} (0, \Sigma_{**} - \Sigma_{*\dagger}\Sigma_{\dagger\dagger}^{-1}\Sigma_{\dagger*}) \\
\pmb{\epsilon} &= Z^{-1} \begin{bmatrix}
\pmb{0} \\
\pmb{\eta^{*}}
\end{bmatrix},
\end{aligned}
$$ where subscripts on the covariance matrices indicate partitions so that $\Sigma_{*\dagger}$ is the sub-matrix of $\Sigma$ with rows corresponding to $\pmb{\eta^{*}}$ and columns to $\pmb{\eta^{\dagger}}$.

## Correlated period parameters for males and females {-}
When both sexes are modelled together, the period innovations for each sex retain separate variance parameters, but are assumed to be joint multivariate normal, with the correlation determined by parameter $\rho$. The joint distribution for the period innovations $\pmb{\epsilon}$ is therefore as follows:

$$
\begin{aligned}
 \begin{bmatrix}
           \pmb{\epsilon_{\kappa f}} \\
           \pmb{\epsilon_{\kappa m}}
         \end{bmatrix}
         &\sim \text{Multivariate Normal} \left( \textbf{0}, P \right) \\
         P &= \begin{bmatrix}
I_T \sigma^2_{\kappa f}& I_T\sigma_{\kappa m}\sigma_{\kappa f}\rho \\
I_T\sigma_{\kappa m}\sigma_{\kappa f}\rho&I_T \sigma^2_{\kappa m}
\end{bmatrix} \\
                  \rho &\sim \text{Beta}(1,1),
\end{aligned}$$ where $I_T$ is the identity matrix of dimension $T$, the number of periods, and $\pmb{\epsilon_{\kappa m}}$ and $\pmb{\epsilon_{\kappa f}}$ refer to period innovations for males and females respectively. The prior distribution of the period parameters conditional on the constraints is obtained in a similar way to the single-sex case. The individual innovation vectors for each sex are first transformed to vectors $\pmb{\eta_f}$ and $\pmb{\eta_m}$. The implied joint multivariate distribution can then be conditioned on the constraints holding true for both sexes in the same way as before:
$$
\begin{aligned}
\pmb{\eta} &= \begin{bmatrix}
\pmb{\eta^{f\dagger}} \\
\pmb{\eta^{f*}} \\
\pmb{\eta^{m\dagger}} \\
\pmb{\eta^{m*}}
\end{bmatrix}
 = X \pmb{\epsilon} \\
 X &= \begin{bmatrix}
Z & 0 \\
0 & Z 
\end{bmatrix} \\
\Xi &= XPX^{T} \\
\pmb{\eta} &\sim \text{MVN} (\pmb{0}, \Xi) \\
\pmb{\eta_{.*}} | (\pmb{\eta_{.\dagger}} = \textbf{0}) &\sim \text{N} (0, \Xi_{**} - \Xi_{*\dagger}\Xi_{\dagger\dagger}^{-1}\Xi_{\dagger*}). \\
\end{aligned}
$$



## Cohort Parameters {-}

Cohort effects are modelled as p-splines, with innovations normally distributed, so that
$$
\begin{aligned}
s_{\gamma}(t-x) &= \pmb{\beta}^{\gamma}\pmb{b}(t-x) \\
\beta^{\gamma}_{i} &= \beta^{\gamma}_{i - 1} + \epsilon^{\gamma}_{i} \\
\epsilon^{\gamma}_{i} &\sim \text{Normal}(0, \sigma_{\gamma}^{2})
\end{aligned}
$$ with $B(.)$ giving the B-spline basis function, and $i$ indexes the individual basis functions.
As with the period effects, a matrix $C$ is describes the constraints on the smooth function $s_{\gamma}$, applying to the first, second, and final elements of the parameter vector.
$$
\begin{aligned}
C = \begin{bmatrix}
1 & 0 & 0 & 0 & \dots & 0 & 0 \\
1 & 1 & 1 & 1 & \dots & 1 & 1 \\
0 & 0 & 0 & 0 & \dots & 0 & 1 \\
\end{bmatrix},
\end{aligned}
$$
The constraints hold when
$$
\begin{aligned}
C\pmb{s_{\gamma}} &= \pmb{0} \\
CBS\pmb{\epsilon^{\gamma}} &= \pmb{0}.
\end{aligned}
$$
A new parameter vector $\pmb{\eta}^{\gamma}$ is obtained as for the period effects 
$$
\begin{aligned}
\pmb{\eta}^{\gamma} &= W\pmb{\epsilon}^{\gamma} \\
\pmb{\eta}^{\gamma} &= \begin{bmatrix}
\pmb{\eta^{\gamma\dagger}} \\
\pmb{\eta^{\gamma*}}\\
\pmb{\eta^{\gamma\ddagger}} \\
\end{bmatrix}\\
\pmb{\eta^{\gamma}} &\sim \text{MVN}(\pmb{0}, WW^{T}\sigma_{\gamma}^{2}).
\end{aligned}
$$
The matrix $W$ is an identity matrix with the first, second and final rows replaced by the rows of the matrix $CBS$, where $B$ is the matrix of basis functions $\pmb{b}(.)$ evaluated for each cohort.
A distribution for $\eta^{\gamma*}$ given the constraints can now be constructed by conditioning on $\pmb{\eta}^{\gamma\dagger} = \pmb{\eta}^{\gamma\ddagger} = 0$, in the same manner as for the period effects. New cohort basis function innovations can be drawn from the normal distribution with mean $0$ and variance $\sigma_{\gamma}^{2}$.
